apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    type: db-data
spec:
  storageClassName: manual
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /db-data/
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi